export enum ExceptionsEnum {
    DISABLE_USER = 'DISABLE_USER',
    LOCKED_USER = 'LOCKED_USER',
    ACCESS_DENIED = 'ACCESS_DENIED',
    DATA_NOT_FOUND = 'DATA_NOT_FOUND',
    BAD_CREDENTIALS = 'BAD_CREDENTIALS',
    TECHNICAL_ERROR = 'TECHNICAL_ERROR',
    UNAUTHORIZED = 'UNAUTHORIZED',
    BAD_REQUEST = 'BAD_REQUEST',
}