export enum RoleEnum {
    // DASHBOARD
    ROLE_DASHBOARD_VIEW = "ROLE_DASHBOARD_VIEW",

    // TICKET MANAGEMENT
    ROLE_TICKET_VIEW = "ROLE_TICKET_VIEW",
    ROLE_TICKET_CREATE = "ROLE_TICKET_CREATE",
    ROLE_TICKET_UPDATE = "ROLE_TICKET_UPDATE",
    ROLE_TICKET_DELETE = "ROLE_TICKET_DELETE",
    ROLE_TICKET_CLOSE = "ROLE_TICKET_CLOSE",
    ROLE_TICKET_WATCH = "ROLE_TICKET_WATCH",
    ROLE_TICKET_TAKE_CHARGE = "ROLE_TICKET_TAKE_CHARGE",
    ROLE_TICKET_ASSIGN = "ROLE_TICKET_ASSIGN",
    ROLE_TICKET_REOPEN = "ROLE_TICKET_REOPEN",
    ROLE_TICKET_CONSIDER_RESOLVED = "ROLE_TICKET_CONSIDER_RESOLVED",
    ROLE_TICKET_LOCK = "ROLE_TICKET_LOCK",
    ROLE_TICKET_READONLY = "ROLE_TICKET_READONLY",
    ROLE_TICKET_UPDATE_STATUS = "ROLE_TICKET_UPDATE_STATUS",
    ROLE_TICKET_VIEW_PRIVATE = "ROLE_TICKET_VIEW_PRIVATE",
    ROLE_TICKET_UPDATE_VISIBILITY = "ROLE_TICKET_UPDATE_VISIBILITY",
    ROLE_TICKET_VIEW_PROBLEM_VERSIONS = "ROLE_TICKET_VIEW_PROBLEM_VERSIONS",
    ROLE_TICKET_REMOVE_PROBLEM_VERSION = "ROLE_TICKET_REMOVE_PROBLEM_VERSION",
    ROLE_TICKET_PIN_PROBLEM = "ROLE_TICKET_PIN_PROBLEM",
    ROLE_TICKET_VIEW_WATCHERS = "ROLE_TICKET_VIEW_WATCHERS",
    ROLE_TICKET_ADD_WATCHER = "ROLE_TICKET_ADD_WATCHER",
    ROLE_TICKET_REMOVE_WATCHER = "ROLE_TICKET_REMOVE_WATCHER",
    ROLE_TICKET_CHANGE_ASSIGN_STATE = "ROLE_TICKET_CHANGE_ASSIGN_STATE",
    ROLE_TICKET_POSITION_AUTO_ASSIGNED = "ROLE_TICKET_POSITION_AUTO_ASSIGNED",
    ROLE_TICKET_VIEW_OTHERS = "ROLE_TICKET_VIEW_OTHERS",
    ROLE_TICKET_PRINT_REPORTS = "ROLE_TICKET_PRINT_REPORTS",
    ROLE_TICKET_EXPORT = "ROLE_TICKET_EXPORT",
    ROLE_TICKET_VIEW_HISTORY = "ROLE_TICKET_VIEW_HISTORY",

    // PROJECT MANAGEMENT
    ROLE_PROJECT_VIEW = "ROLE_PROJECT_VIEW",
    ROLE_PROJECT_CREATE = "ROLE_PROJECT_CREATE",
    ROLE_PROJECT_UPDATE = "ROLE_PROJECT_UPDATE",
    ROLE_PROJECT_DELETE = "ROLE_PROJECT_DELETE",

    // USER MANAGEMENT
    ROLE_USER_VIEW = "ROLE_USER_VIEW",
    ROLE_USER_CREATE = "ROLE_USER_CREATE",
    ROLE_USER_UPDATE = "ROLE_USER_UPDATE",
    ROLE_USER_DELETE = "ROLE_USER_DELETE",

    // HABILITATION MANAGEMENT
    ROLE_HABILITATION_VIEW = "ROLE_HABILITATION_VIEW",
    ROLE_HABILITATION_CREATE = "ROLE_HABILITATION_CREATE",
    ROLE_HABILITATION_UPDATE = "ROLE_HABILITATION_UPDATE",
    ROLE_HABILITATION_DELETE = "ROLE_HABILITATION_DELETE",

    // ACCESS HISTORY MANAGEMENT
    ROLE_ACCESS_HISTORY_VIEW = "ROLE_ACCESS_HISTORY_VIEW",
    ROLE_ACCESS_HISTORY_CREATE = "ROLE_ACCESS_HISTORY_CREATE",
    ROLE_ACCESS_HISTORY_UPDATE = "ROLE_ACCESS_HISTORY_UPDATE",
    ROLE_ACCESS_HISTORY_DELETE = "ROLE_ACCESS_HISTORY_DELETE",

    // EMAIL NOTIFICATIONS MANAGEMENT
    ROLE_EMAIL_NOTIFICATIONS_VIEW = "ROLE_EMAIL_NOTIFICATIONS_VIEW",
    ROLE_EMAIL_NOTIFICATIONS_CREATE = "ROLE_EMAIL_NOTIFICATIONS_CREATE",
    ROLE_EMAIL_NOTIFICATIONS_UPDATE = "ROLE_EMAIL_NOTIFICATIONS_UPDATE",
    ROLE_EMAIL_NOTIFICATIONS_DELETE = "ROLE_EMAIL_NOTIFICATIONS_DELETE",

    // CATEGORY MANAGEMENT
    ROLE_CATEGORY_VIEW = "ROLE_CATEGORY_VIEW",
    ROLE_CATEGORY_CREATE = "ROLE_CATEGORY_CREATE",
    ROLE_CATEGORY_UPDATE = "ROLE_CATEGORY_UPDATE",
    ROLE_CATEGORY_DELETE = "ROLE_CATEGORY_DELETE",


    ROLE_GESTION_UTILISATEUR = "ROLE_GESTION_UTILISATEUR",
    ROLE_ASSISTANT_CONVERSATIONNEL = "ROLE_ASSISTANT_CONVERSATIONNEL",

    //DATABASE

    ROLE_AFFICHER_DATABASE = "ROLE_AFFICHER_DATABASE"

}
