package com.binewvision.Motulbackend.enums;

public enum ExceptionsEnum {
    DISABLE_USER,
    LOCKED_USER,
    ACCESS_DENIED,
    DATA_NOT_FOUND,
    BAD_CREDENTIALS,
    TECHNICAL_ERROR,
    UNAUTHORIZED,
    BAD_REQUEST,
    PATIENT_ALREADY_EXISTS,
    OPERATION_NOT_ALLOWED,
    FILE_EXTENSION_NOT_SUPPORTED,
    FILE_SIZE_LIMIT_EXCEEDED,
    INCORRECT_OLD_PASSWORD,
    NEW_PASSWORD_MATCHES_OLD,
    USER_REACHED_MAX_ATTEMPTS
}
