# Stage 2: Serve with Nginx
FROM nginx:stable

# Copy build output to Nginx html folder
COPY ./dist/ /usr/share/nginx/html/

# Copy custom Nginx config if needed
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
